import * as fs from 'node:fs/promises';
import * as path from 'node:path';

const DATA_DIR = path.resolve(__dirname, '..', 'data');
const OUTPUT_PATH = path.resolve(__dirname, '..', 'src', 'bundled-data.ts');

function processDomainList(content: string): string[] {
    const domains = new Set<string>();

    for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (trimmed.length === 0 || trimmed.startsWith('#')) {
            continue;
        }
        domains.add(trimmed.toLowerCase());
    }

    return Array.from(domains).sort();
}

(async () => {
    try {
        const blocklistContent = await fs.readFile(path.join(DATA_DIR, 'BLOCKLIST'), 'utf8');
        const allowlistContent = await fs.readFile(path.join(DATA_DIR, 'ALLOWLIST'), 'utf8');

        const blocklist = processDomainList(blocklistContent);
        const allowlist = processDomainList(allowlistContent);

        const output = [
            '/* eslint-disable */',
            '// Auto-generated by scripts/generate-bundled-data.ts — do not edit manually.',
            '',
            '/** Bundled blocklist domains. */',
            `export const BUNDLED_BLOCKLIST: string[] = ${JSON.stringify(blocklist)};`,
            '',
            '/** Bundled allowlist domains. */',
            `export const BUNDLED_ALLOWLIST: string[] = ${JSON.stringify(allowlist)};`,
            ''
        ].join('\n');

        await fs.writeFile(OUTPUT_PATH, output, 'utf8');

        // eslint-disable-next-line no-console
        console.log(`Generated bundled-data.ts: ${blocklist.length} blocked, ${allowlist.length} allowed.`);
        process.exit(0);
    } catch (error) {
        // eslint-disable-next-line no-console
        console.error('Error generating bundled data:', error instanceof Error ? error.message : error);
        process.exit(1);
    }
})();
